# permissions for end users to view bigtablerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bigtablerestore-viewer-role
rules:
- apiGroups:
  - ivy.dev
  resources:
  - bigtablerestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ivy.dev
  resources:
  - bigtablerestores/status
  verbs:
  - get
