# permissions for end users to edit bigtablerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bigtablerestore-editor-role
rules:
- apiGroups:
  - ivy.dev
  resources:
  - bigtablerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ivy.dev
  resources:
  - bigtablerestores/status
  verbs:
  - get
